In [ ]:
import pandas as pd
import os
import numpy as np

In [3]:
data_2018_path = '/Users/jk/Library/CloudStorage/Nextcloud-julian@hendrikklug․xyz/geneva_stroke_unit_dataset/stroke_registry/original_extraction/062022/SSR_cases_of_2018.xlsx'
data_2019_path = '/Users/jk/Library/CloudStorage/Nextcloud-julian@hendrikklug․xyz/geneva_stroke_unit_dataset/stroke_registry/original_extraction/062022/SSR_cases_of_2019.xlsx'
data_2020_path = '/Users/jk/Library/CloudStorage/Nextcloud-julian@hendrikklug․xyz/geneva_stroke_unit_dataset/stroke_registry/original_extraction/062022/SSR_cases_of_2020.xlsx'
data_2021_path = '/Users/jk/Library/CloudStorage/Nextcloud-julian@hendrikklug․xyz/geneva_stroke_unit_dataset/stroke_registry/original_extraction/062022/SSR_cases_of_2021.xlsx'

In [4]:
modifications_path = '/Users/jk/Library/CloudStorage/Nextcloud-julian@hendrikklug․xyz/geneva_stroke_unit_dataset/stroke_registry/post_hoc_modifications.xlsx'

In [16]:
os.path.join(os.path.dirname(os.path.dirname(data_2018_path)), 'post_hoc_modified')

'/Users/jk/Library/CloudStorage/Nextcloud-julian@hendrikklug․xyz/geneva_stroke_unit_dataset/stroke_registry/original_extraction/post_hoc_modified'

In [18]:
# skipping empty rows at the beginning
data_2018_df = pd.read_excel(data_2018_path, skiprows=[0, 1, 2, 3, 4, 5, 7])
data_2019_df = pd.read_excel(data_2019_path, skiprows=[0, 1, 2, 3, 4, 5, 7])
data_2020_df = pd.read_excel(data_2020_path, skiprows=[0, 1, 2, 3, 4, 5, 7])
data_2021_df = pd.read_excel(data_2021_path, skiprows=[0, 1, 2, 3, 4, 5, 7])

Verify all columns correspond

In [19]:
(
np.all(data_2018_df.columns == data_2019_df.columns),
np.all(data_2018_df.columns == data_2020_df.columns),
np.all(data_2018_df.columns == data_2021_df.columns)
)

(True, True, True)

In [20]:
stroke_registry_df = pd.concat([data_2018_df, data_2019_df, data_2020_df, data_2021_df])

In [22]:
modifications_df = pd.read_excel(modifications_path)

In [23]:
stroke_registry_df

,Unnamed: 0,Case ID,Centre,Entry date,Entry person,Patient refuses use of data for research,Last name,First name,DOB,Type of event,...,3M NIHSS,3M Stroke,3M Stroke date,3M ICH,3M ICH date,3M Death,3M Death date,3M Death cause,3M Epileptic seizure,3M Epileptic seizure date
0,1,SSR-HUG-023804235,HUG Genève,20180525,Emmanuel Carrera,yes,NaN,NaN,19310702.0,Ischemic stroke,...,NaN,no,NaN,no,NaN,yes,20180731.0,other vascular death,no,NaN
1,2,SSR-HUG-1002048465,HUG Genève,20181029,Emmanuel Carrera,NaN,NaN,NaN,19471020.0,Transient ischemic attack,...,0.0,no,NaN,no,NaN,no,NaN,NaN,no,NaN
2,3,SSR-HUG-1002910806,HUG Genève,20181123,Emmanuel Carrera,NaN,NaN,NaN,19290317.0,Transient ischemic attack,...,NaN,no,NaN,no,NaN,no,NaN,NaN,no,NaN
3,4,SSR-HUG-1005030884,HUG Genève,20181108,Emmanuel Carrera,NaN,NaN,NaN,19331031.0,Ischemic stroke,...,2.0,no,NaN,no,NaN,no,NaN,NaN,NaN,NaN
4,5,SSR-HUG-1005303803,HUG Genève,20180922,Emmanuel Carrera,NaN,NaN,NaN,19451125.0,Intracerebral hemorrhage,...,NaN,no,NaN,no,NaN,no,NaN,NaN,no,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1256,1257,SSR-HUG-991506305,HUG Genève,20210428,Marie-Christine Zefferer,NaN,NaN,NaN,19700503.0,Ischemic stroke,...,0.0,no,NaN,no,NaN,no,NaN,NaN,no,NaN
1257,1258,SSR-HUG-9931125546,HUG Genève,20210106,Marie-Christine Zefferer,NaN,NaN,NaN,19580505.0,Ischemic stroke,...,NaN,no,NaN,no,NaN,no,NaN,NaN,NaN,NaN
1258,1259,SSR-HUG-9935526604,HUG Genève,20210612,Marie-Christine Zefferer,NaN,NaN,NaN,19420214.0,Ischemic stroke,...,NaN,no,NaN,no,NaN,yes,20210626.0,unknown,NaN,NaN
1259,1260,SSR-HUG-9954190962,HUG Genève,20210917,Juliette Cloppet Mouchet,yes,NaN,NaN,19321130.0,Ischemic stroke,...,1.0,no,NaN,no,NaN,no,NaN,NaN,no,NaN
1260,1261,SSR-HUG-999801446,HUG Genève,20210805,Marie-Christine Zefferer,NaN,NaN,NaN,19431109.0,Ischemic stroke,...,0.0,no,NaN,no,NaN,no,NaN,NaN,no,NaN

In [24]:
modifications_df

,Case ID,modified_column,new_value,reason
0,SSR-HUG-978036574409,Onset date,20180307,wrong year in stroke onset date
1,SSR-HUG-3802346696,Type of event,Stroke or TIA mimic,low flow state in patient with cardiac arrest
2,SSR-HUG-978036574409,Sex,Female,no sex stated
3,SSR-HUG-4070344159,IVT start date,20200107,wrong year in IVT date
4,SSR-HUG-3403543116,Onset date,20200825,wrong stroke onset date
...,...,...,...,...
115,SSR-HUG-971714483044,Type of event,Stroke or TIA mimic,peripheral vertigo
116,SSR-HUG-985681686370,Type of event,Stroke or TIA mimic,fonctionnel
117,SSR-HUG-972059737683,Arrival at hospital,20180105,wrong arrival date
118,SSR-HUG-515534935,Referral,In-hospital event,intra HUG
119,SSR-HUG-4055278341,IVT start date,20181020,wrong IVT date

In [25]:
for index, row in modifications_df.iterrows():
    print(f'Modifying {row["modified_column"]} for {row["Case ID"]}, because {row["reason"]}')
    stroke_registry_df.loc[stroke_registry_df['Case ID'] == row['Case ID'], row['modified_column']] = row['new_value']

Modifying Onset date for SSR-HUG-978036574409, because wrong year in stroke onset date
Modifying Type of event for SSR-HUG-3802346696, because low flow state in patient with cardiac arrest
Modifying Sex for SSR-HUG-978036574409, because no sex stated
Modifying IVT start date for SSR-HUG-4070344159, because wrong year in IVT date
Modifying Onset date for SSR-HUG-3403543116, because wrong stroke onset date
Modifying Onset date for SSR-HUG-985513483834, because wrong year in stroke onset date
Modifying Onset date for SSR-HUG-10557546545, because wrong year in stroke onset date
Modifying Onset date for SSR-HUG-987214292246, because wrong year in stroke onset date
Modifying Case ID for SSR-HUG-20015697, because wrong patient id and eds
Modifying DOB for SSR-HUG-204632067, because wrong birth date
Modifying Case ID for SSR-HUG-97042898, because wrong patient id and eds
Modifying DOB for SSR-HUG-10777869400, because wrong birth date
Modifying Case ID for SSR-HUG-140044131752, because wrong patient id and eds
Modifying Type of event for SSR-HUG-10409352, because not a stroke
Modifying Arrival at hospital for SSR-HUG-2309683957, because wrong arrival date
Modifying Arrival at hospital for SSR-HUG-2491389634, because wrong arrival date
Modifying Onset date for SSR-HUG-3556758880, because wrong stroke onset date
Modifying Time of symptom onset known for SSR-HUG-3556758880, because wrong stroke onset date
Modifying Arrival at hospital for SSR-HUG-4055278341, because wrong arrival date
Modifying Onset date for SSR-HUG-4055278341, because wrong stroke onset date
Modifying Arrival at hospital for SSR-HUG-4340757793, because 2 admissions but second admission is in stroke center
Modifying Type of event for SSR-HUG-5839238006, because probable epileptic event
Modifying Arrival at hospital for SSR-HUG-720706547, because 2 admissions but second admission is in stroke center
Modifying Arrival at hospital for SSR-HUG-8590061277, because wrong arrival date
Modifying Onset date for SSR-HUG-8590061277, because wrong stroke onset date
Modifying Arrival at hospital for SSR-HUG-973839775507, because 2 admissions but second admission is in stroke center
Modifying Type of event for SSR-HUG-10699579777, because fluctuation / dementia
Modifying Onset date for SSR-HUG-10699578052, because wrong stroke onset date
Modifying Arrival at hospital for SSR-HUG-10699578052, because wrong arrival date
Modifying Referral for SSR-HUG-10699578052, because comes from nursing home
Modifying Discharge date for SSR-HUG-10699578052, because wrong discharge date
Modifying Arrival at hospital for SSR-HUG-10764000048, because 2 admissions but second admission is in stroke center
Modifying Type of event for SSR-HUG-1079569402, because duplicate
Modifying Onset date for SSR-HUG-1715477760, because wrong stroke onset date
Modifying Onset date for SSR-HUG-1715478463, because wrong stroke onset date
Modifying Time of symptom onset known for SSR-HUG-1715477760, because wrong stroke onset date
Modifying Time of symptom onset known for SSR-HUG-1715478463, because wrong stroke onset date
Modifying Arrival at hospital for SSR-HUG-192702020, because 2 admissions but second admission is in stroke center
Modifying Time of symptom onset known for SSR-HUG-2660312067, because unknown onset date
Modifying Time of symptom onset known for SSR-HUG-2732236148, because unknown onset date
Modifying Arrival at hospital for SSR-HUG-3263541547, because wrong arrival date
Modifying Time of symptom onset known for SSR-HUG-3263541547, because unknown onset date
Modifying Arrival at hospital for SSR-HUG-4028112601, because wrong arrival date
Modifying Arrival time for SSR-HUG-4028112601, because wrong arrival date
Modifying Onset date for SSR-HUG-4028112601, because unknown onset date
Modifying Time of symptom onset known for SSR-HUG-4028112601, because unknown onset date
Modifying Onset time for SSR-HUG-4028112601, because unknown onset date
Modifying Discharge date for SSR-HUG-4028112601, because wrong discharge date
Modifying Type of event for SSR-HUG-5313220170, because duplicate
Modifying Time of symptom onset known for SSR-HUG-5313228658, because unknown onset date
Modifying Type of event for SSR-HUG-629771569, because duplicate
Modifying Type of event for SSR-HUG-8873129592, because duplicate
Modifying Type of event for SSR-HUG-972693949040, because duplicate
Modifying Type of event for SSR-HUG-1444006, because duplicate
Modifying Initial hospitalization for SSR-HUG-587527539, because outpatient management
Modifying Type of event for SSR-HUG-675428330, because duplicate
Modifying Type of event for SSR-HUG-8938560732, because duplicate
Modifying Referral for SSR-HUG-8938569691, because intra HUG
Modifying Type of event for SSR-HUG-2003779754, because mimic
Modifying Type of event for SSR-HUG-4546981901, because seizure
Modifying Type of event for SSR-HUG-977067379963, because TIA
Modifying Arrival at hospital for SSR-HUG-852817246, because wrong onset date
Modifying Onset date for SSR-HUG-1120871263, because unknown onset date
Modifying Onset time for SSR-HUG-1120871263, because unknown onset date
Modifying Type of event for SSR-HUG-1120873178, because post stroke recrudescence syndrome
Modifying Initial hospitalization for SSR-HUG-1120873178, because retour à beau sejour
Modifying 3M mRS for SSR-HUG-1902478788, because in-hospital death
Modifying 3M Death for SSR-HUG-1902478788, because in-hospital death
Modifying 3M Death date for SSR-HUG-1902478788, because in-hospital death
Modifying Onset time for SSR-HUG-1902478788, because wrong onset time
Modifying Discharge date for SSR-HUG-4499090003, because wrong discharge date
Modifying Discharge time for SSR-HUG-4499090003, because wrong discharge date
Modifying Time of symptom onset known for SSR-HUG-9360284802, because wrong onset time
Modifying Onset time for SSR-HUG-9360284802, because wrong onset time
Modifying Discharge date for SSR-HUG-9360284802, because wrong discharge date
Modifying Type of event for SSR-HUG-9360284802, because seizure
Modifying Discharge date for SSR-HUG-978321177144, because wrong discharge date
Modifying Discharge time for SSR-HUG-978321177144, because wrong discharge date
Modifying Discharge date for SSR-HUG-986495256756, because wrong discharge date
Modifying Onset date for SSR-HUG-1561907537, because unknown onset date
Modifying Onset time for SSR-HUG-1561907537, because unknown onset date
Modifying Type of event for SSR-HUG-1561906687, because duplicate
Modifying Time of symptom onset known for SSR-HUG-1561906972, because unknown onset date
Modifying Onset date for SSR-HUG-1561906972, because unknown onset date
Modifying Onset time for SSR-HUG-1561906972, because unknown onset date
Modifying Time of symptom onset known for SSR-HUG-98553980615, because unknown onset date
Modifying Referral for SSR-HUG-98553980615, because Self referral
Modifying Arrival at hospital for SSR-HUG-9100900087, because wrong arrival date
Modifying Arrival at hospital for SSR-HUG-2314980921, because wrong arrival date
Modifying Type of event for SSR-HUG-1510689697, because mimic
Modifying Type of event for SSR-HUG-151662396239, because duplicate
Modifying Time of symptom onset known for SSR-HUG-5913704347, because symptom onset known
Modifying Onset date for SSR-HUG-5913704347, because symptom onset known
Modifying Onset time for SSR-HUG-5913704347, because symptom onset known
Modifying 1st brain imaging type for SSR-HUG-5913704347, because 1st imaging wrong
Modifying 1st brain imaging date for SSR-HUG-5913704347, because 1st imaging wrong
Modifying 1st brain imaging time for SSR-HUG-5913704347, because 1st imaging wrong
Modifying Referral for SSR-HUG-5913704347, because intra HUG
Modifying Referral for SSR-HUG-6769083618, because referred by permanence
Modifying Onset date for SSR-HUG-8024074199, because wrong onset date
Modifying Onset time for SSR-HUG-8024074199, because wrong onset time
Modifying Onset date for SSR-HUG-9845660895, because wrong onset date
Modifying Onset time for SSR-HUG-9845660895, because wrong onset time
Modifying Onset date for SSR-HUG-1838852252, because wrong onset date
Modifying Onset time for SSR-HUG-1838852252, because wrong onset time
Modifying Onset date for SSR-HUG-4528671733, because wrong onset date
Modifying Onset time for SSR-HUG-4528671733, because wrong onset time
Modifying Onset date for SSR-HUG-515534935, because wrong onset date
Modifying Onset time for SSR-HUG-515534935, because wrong onset time
Modifying Referral for SSR-HUG-7518348109, because Referred by centre mémoire
Modifying Referral for SSR-HUG-985490107474, because Referred by center in France
Modifying Type of event for SSR-HUG-10115717973, because subendymoma
Modifying Type of event for SSR-HUG-1669571359, because trouble de la marche
Modifying Type of event for SSR-HUG-2570526415, because hemodynamically significant stenosis
Modifying Type of event for SSR-HUG-971282175075, because delirium
Modifying Type of event for SSR-HUG-971714483044, because peripheral vertigo
Modifying Type of event for SSR-HUG-985681686370, because fonctionnel
Modifying Arrival at hospital for SSR-HUG-972059737683, because wrong arrival date
Modifying Referral for SSR-HUG-515534935, because intra HUG
Modifying IVT start date for SSR-HUG-4055278341, because wrong IVT date

In [27]:
stroke_registry_df.to_excel(os.path.join('/Users/jk/Downloads', 'stroke_registry_post_hoc_modified.xlsx'), index=False)